---
- name: Deploy Node.js service
  apt:
    update_cache: yes
    upgrade: dist

- name: Ensure Node.js is installed
  apt:
    name:
      - nodejs
      - npm
    state: present
    update_cache: yes

- name: Clone the repository
  git:
    repo: "{{ app_repo }}"
    dest: "{{ app_path }}"
    version: main
    force: yes

- name: Dummy build step
  command: npm install
  args:
    chdir: "{{ app_path }}/src"

- name: Create systemd service for Node.js app
  copy:
    dest: "/etc/systemd/system/{{ app_name }}.service"
    content: |
      [Unit]
      Description=Node.js Service {{ app_name }}
      After=network.target

      [Service]
      ExecStart=/usr/bin/npm start
      WorkingDirectory={{ app_path }}/src
      Restart=always
      RestartSec=5
      User=www-data
      Environment=NODE_ENV=production PORT={{ node_app_port }}

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to pick up new service
  command: systemctl daemon-reload

- name: Enable and start the Node.js service
  systemd:
    name: "{{ app_name }}"
    enabled: yes
    state: started

- name: Restart Node.js service to load new code
  systemd:
    name: nodejs-service
    state: restarted
