name: Deploy Node.js App with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my-node-app ./server

      - name: Run container
        run: |
          docker run -d --name test-container \
            -p 3000:3000 \
            -e PORT=3000 \
            -e USERNAME="${{ secrets.USERNAME }}" \
            -e PASSWORD="${{ secrets.PASSWORD }}" \
            -e SECRET_MESSAGE="${{ secrets.SECRET_MESSAGE }}" \
            my-node-app
          
          # Give it a moment to start
          sleep 5

      - name: Test app endpoints
        run: |
          echo "Testing public endpoint..."
          curl -f http://localhost:3000

          echo "Testing protected endpoint..."
          curl -f -u "${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}" http://localhost:3000/secret

      - name: Stop and remove container
        if: always()
        run: |
          docker stop test-container
          docker rm test-container

