name: Deploy Node.js App with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    env:
      IMAGE_NAME: docker.io/therealpad/my-node-app
      CONTAINER_NAME: my-node-app
      PORT: 3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest ./server

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT || 22 }}
          debug: true
          script: |
            set -xe
            ls; echo "LS done" >&2
            echo "Pulling latest Docker image..."
            docker pull $IMAGE_NAME:latest

            echo "Deployment complete!"
